name: masir_balini
description: اپ آفلاین فارسی برنامه جامع روان‌شناسی بالینی
publish_to: none
version: 1.0.0+1

environment:
  sdk: ">=3.9.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  sqflite: ^2.4.3
  path: ^1.9.1
  path_provider: ^2.1.6
  file_picker: ^8.1.7
  excel: ^4.0.6
  fl_chart: ^1.2.0
  shamsi_date: ^1.1.1
  shared_preferences: ^2.5.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - assets/seed/normalized_seed_v2.json
    - assets/seed/clinical_psychology_plan_1405_professional_final.xlsx
    - assets/branding/app_icon.png
    - assets/branding/app_icon_foreground.png
    - assets/ui/ui_reference.png
    - assets/ui/ui_concept_alt.png

flutter_launcher_icons:
  android: true
  ios: false
  image_path: assets/branding/app_icon.png
  adaptive_icon_background: "#F4F1FF"
  adaptive_icon_foreground: assets/branding/app_icon_foreground.png
  adaptive_icon_foreground_inset: 18
  min_sdk_android: 23
